language: php

dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - nightly

env:
  # - WP_VERSION=latest WP_MULTISITE=0
  # - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=nightly

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 8.0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - php --version
  - echo ${TRAVIS_PHP_VERSION}
  - echo ${TRAVIS_PHP_VERSION:0:3}
  # WordPress only compatible with PHPUnit 7.x
  - |
    case ${TRAVIS_PHP_VERSION:0:3} in
    7.4 | 7.3 | 7.2)
      composer global require "phpunit/phpunit:^7"
      ;;
    7.1 | 7.0)
      composer global require "phpunit/phpunit:^6"
      ;;
    5.6)
      composer global require "phpunit/phpunit:^4"
      ;;
    *)
      composer global require "phpunit/phpunit:^9"
      ;;
    esac

  - $HOME/.composer/vendor/bin/phpunit --version
  - phpunit --version

script:
- phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist"
- composer install --prefer-dist --no-interaction
- phpunit

before_deploy:
  - composer install --prefer-dist --no-interaction --no-dev
  - git archive -o /tmp/github-updater-${TRAVIS_TAG}.zip --prefix=github-updater/ ${TRAVIS_COMMIT}
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: /tmp/github-updater-${TRAVIS_TAG}.zip
  on:
    tags: true
    php: 7.3
